---
title: "ACTIVIDAD 2 - UD2"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

# Actividad 2 - UD2
Carga el dataset **titanic** con el comando y haz un sumario
```{r}
# install.packages("titanic")
# data("titanic_train")
# df <- titanic_train
# head(df)
# str(df)
```
- Transforma las variables que sean factores en factores. Si son ordinales usa *ordered* para crear factores ordenados. Recuerda usar lapply.
- Representa en un qplot la edad frente a la tarifa, y en un segundo qplot lo mismo pero con la clave de la clase en la que viajaban. Represéntalo a su vez factorizándolo por *Sex* y *Embarked*
- Pinta un boxplot de la edad agrupado según *Sex*
- Pinta un barplot que represente la supervivencia en cada *Pclass* coloreando las barras según esta
- Pinta la supervivencia en función de la categoría *Sex*, ¿qué observas?
- Pinta la supervivencia en función de la categoría *Pclass*, ¿qué se aprecia?
- Crea un histograma de *Age*, ¿qué observas?
- Crea una agrupación de los datos usando `dplyr` de *Sex*  y *Pclass*. Haz sumarios de media, conteo y mediana. ¿Qué podrías decir de los resultados? ¿Hay suficiente muestra para sacar conclusiones en todas las categorías creadas al combinar la edad y la clase?