---
title: "R Notebook"
output: html_notebook
---

```{r}
url <- "http://www.statsci.org/data/general/flicker.txt"
flicker <- read.csv(url,sep="\t")
write.csv(flicker,"flicker.csv")
```

```{r}
flicker  #parpadeos
```

```{r}
#Tienen que ser variables categóricas
is.factor(flicker$Colour)
```

```{r}
levels(flicker$Colour)
```

```{r}
unclass(flicker$Colour)
```

```{r}
attach(flicker) #The database is attached to the R search path. This means that the database is searched by R when evaluating a variable
boxplot(Flicker ~ Colour, ylab = "Flicker")

```

```{r}
stripchart(Flicker ~ Colour, vertical=TRUE)
```

Agrupamos y damos la media y desviación típica según cada factor
```{r}
meansd <- function(x) c(mean=mean(x), sd=sd(x))
by(Flicker, Colour, FUN=meansd)
```

Aplicamos un ANOVA para dictaminar si son iguales
```{r}
 #test asumiendo varianzas distintas concluye que no tienen medias iguales por ser p <0.05
oneway.test(Flicker ~ Colour)
```

```{r}
#test asumiendo varianzas iguales concluye que no tienen medias iguales
oneway.test(Flicker ~ Colour, var.equal=TRUE) 
```

